# Generated by Django 4.2.4 on 2023-08-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('started_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ends_on', models.DateTimeField(auto_now=True, null=True)),
                ('donation_title', models.CharField(max_length=256)),
                ('donation_minimum_amount', models.IntegerField(default=0)),
                ('donation_status', models.SmallIntegerField(default=0)),
                ('donation_description', models.CharField(max_length=256)),
                ('donation_content', models.CharField(max_length=10240)),
                ('donation_image', models.ImageField(upload_to='Donation/%Y/%m/%d')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_donation',
            },
        ),
        migrations.RemoveField(
            model_name='donationheader',
            name='member',
        ),
        migrations.DeleteModel(
            name='DonationDetail',
        ),
        migrations.AlterField(
            model_name='donationdoner',
            name='donation_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
        ),
        migrations.AlterField(
            model_name='donationinquiry',
            name='donation_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
        ),
        migrations.AlterField(
            model_name='donationreply',
            name='donation_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
        ),
        migrations.DeleteModel(
            name='DonationHeader',
        ),
    ]
