# Generated by Django 4.2.4 on 2023-08-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_remove_donationheader_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationdoner',
            old_name='donation_header',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='donationinquiry',
            old_name='donation_header',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='donationreply',
            old_name='donation_header',
            new_name='donation',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donation_status',
        ),
    ]
