# Generated by Django 4.2.4 on 2023-08-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaignreview_campaign_review_image'),
        ('funding', '0004_funding_campaign'),
        ('region', '0003_saferegion'),
        ('donation', '0003_rename_donation_header_donationdoner_donation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('score', models.IntegerField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.funding')),
                ('safety_score_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.safetyscoreheader')),
            ],
            options={
                'db_table': 'tbl_safety_score_detail',
            },
        ),
    ]
