# Generated by Django 4.2 on 2023-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_safetyscoredetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ends_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='started_on',
            field=models.DateTimeField(null=True),
        ),
    ]
