# Generated by Django 4.2.4 on 2023-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donation_ends_on_alter_donation_started_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_sub_image',
            field=models.ImageField(null=True, upload_to='Donation/%Y/%m/%d'),
        ),
    ]
