# Generated by Django 4.2.4 on 2023-08-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_saferegion'),
        ('donation', '0006_donation_donation_sub_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='region.citydetail'),
        ),
        migrations.AddField(
            model_name='donation',
            name='city_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='region.cityheader'),
        ),
    ]
