# Generated by Django 4.2.4 on 2023-08-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding', '0004_funding_campaign'),
        ('member', '0005_rename_funding_inquiry_inquiryanswer_inquiry'),
        ('donation', '0003_rename_donation_header_donationdoner_donation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('pay_amount', models.IntegerField(null=True)),
                ('pay_allowance', models.IntegerField(null=True)),
                ('donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
                ('funding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.funding')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_pay',
            },
        ),
    ]
