# Generated by Django 4.2.4 on 2023-08-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_remove_campaignheader_member_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigninquiry',
            old_name='campaign_header',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='campaignparticipant',
            old_name='campaign_header',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='campaignphoto',
            old_name='campaign_header',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='campaignreview',
            old_name='campaign_header',
            new_name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_status',
        ),
    ]
