# Generated by Django 4.2.4 on 2023-08-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_city_detail_campaign_city_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='member_id',
            new_name='member',
        ),
    ]
