# Generated by Django 4.2.4 on 2023-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_rename_member_id_campaign_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignreview',
            name='campaign_review_image',
            field=models.ImageField(null=True, upload_to='Campaign/Review/%Y/%m/%d'),
        ),
    ]
