# Generated by Django 4.2 on 2023-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaignreview_campaign_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ends_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='started_on',
            field=models.DateTimeField(null=True),
        ),
    ]
