# Generated by Django 4.2.4 on 2023-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
