# Generated by Django 4.2.4 on 2023-08-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_inquiry_inquiryanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiryanswer',
            old_name='funding_inquiry',
            new_name='inquiry',
        ),
    ]
