# Generated by Django 4.2.4 on 2023-08-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_safetyscoreheader'),
        ('member', '0005_rename_funding_inquiry_inquiryanswer_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='city_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='region.citydetail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='city_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='region.cityheader'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_image',
            field=models.ImageField(null=True, upload_to='Member/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
