# Generated by Django 4.2.4 on 2023-08-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('started_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ends_on', models.DateTimeField(auto_now=True, null=True)),
                ('funding_title', models.CharField(max_length=256)),
                ('funding_minimum_amount', models.IntegerField(default=0)),
                ('funding_status', models.SmallIntegerField(default=0)),
                ('funding_description', models.CharField(max_length=256)),
                ('funding_content', models.CharField(max_length=10240)),
                ('funding_image', models.ImageField(upload_to='Funding/%Y/%m/%d')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'tbl_funding',
            },
        ),
        migrations.RemoveField(
            model_name='fundingheader',
            name='member',
        ),
        migrations.DeleteModel(
            name='FundingDetail',
        ),
        migrations.AlterField(
            model_name='fundinginquiry',
            name='funding_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.funding'),
        ),
        migrations.AlterField(
            model_name='fundingreply',
            name='funding_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.funding'),
        ),
        migrations.AlterField(
            model_name='fundingsponsor',
            name='funding_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.funding'),
        ),
        migrations.DeleteModel(
            name='FundingHeader',
        ),
    ]
