# Generated by Django 4.2.4 on 2023-08-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_funding_remove_fundingheader_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundinginquiry',
            old_name='funding_header',
            new_name='funding',
        ),
        migrations.RenameField(
            model_name='fundinginquiry',
            old_name='inquiry_content',
            new_name='funding_inquiry_content',
        ),
        migrations.RenameField(
            model_name='fundinginquiry',
            old_name='inquiry_status',
            new_name='fundinginquiry_status',
        ),
        migrations.RenameField(
            model_name='fundingreply',
            old_name='funding_header',
            new_name='funding',
        ),
        migrations.RenameField(
            model_name='fundingsponsor',
            old_name='funding_header',
            new_name='funding',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='funding_status',
        ),
    ]
