# Generated by Django 4.2.4 on 2023-08-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_rename_campaign_header_campaigninquiry_campaign_and_more'),
        ('funding', '0003_rename_funding_header_fundinginquiry_funding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
    ]
