# Generated by Django 4.2.4 on 2023-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_alter_funding_ends_on_alter_funding_started_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='funding_sub_image',
            field=models.ImageField(null=True, upload_to='Funding/%Y/%m/%d'),
        ),
    ]
