# Generated by Django 4.2.4 on 2023-08-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyScoreHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('strd_yr', models.CharField(max_length=4, null=True)),
                ('pul', models.IntegerField(null=True)),
                ('totl_zrmst', models.IntegerField(null=True)),
                ('safety_score', models.IntegerField(null=True)),
                ('city_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.cityheader')),
            ],
            options={
                'db_table': 'tbl_safety_score_header',
            },
        ),
    ]
