# Generated by Django 4.2.4 on 2023-08-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_safetyscoreheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('safe_region_description', models.CharField(max_length=1024, null=True)),
                ('safe_region_description2', models.CharField(max_length=1024, null=True)),
                ('safe_region_url', models.CharField(max_length=100, null=True)),
                ('safe_region_info', models.CharField(max_length=1024, null=True)),
                ('safe_region_content', models.CharField(max_length=10240, null=True)),
                ('city_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.cityheader')),
            ],
            options={
                'db_table': 'tbl_safe_region',
            },
        ),
    ]
